version: '3.7'

services:
  mysql:
    image: mysql:8.0.23
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 3306

  webapp:
    build:
      context: ./
      dockerfile: ./docker/webapp.dockerfile
    ports:
      - 6000:6000

networks:
  default:
    driver: bridge
